### ISSUE TITLE
Allow login with github on mattermost

### ISSUE THREAD

**Issue by rnestler** [SpaceApi/provisioning#15]
Could we enable login with github with OAuth on mattermost? Makes it easier to login.

**Comment by gidsi** [comment]
So far i just see gitlab support, how do i do it?

**Comment by dbrgn** [comment]
Yeah, doesn't look like it includes a Github OAuth provider: https://docs.mattermost.com/help/getting-started/signing-in.html#sign-in-methods

**Comment by gidsi** [comment]
Closing this until mattermost provides a connector.

**Comment by rnestler** [comment]
GitLab would also be fine for me :)

**Comment by dbrgn** [comment]
Which gitlab? gitlab.com?

**Comment by rnestler** [comment]
Yes, using any other private GitLab instance would be strange, wouldn't it?

**Comment by dbrgn** [comment]
Yep, that's why I'm asking 😄
