### ISSUE TITLE
Is this provisioning complete?

### ISSUE THREAD

**Issue by slopjong** [SpaceApi/provisioning#21]
If I provision a custom host, does it really do *everything* including all the mattermost stuff etc? What is the host `katharina.chaospott.de`?

**Comment by rnestler** [comment]
Yes it setups a complete host. For the mattermost stuff see https://github.com/SpaceApi/provisioning/tree/master/roles/mattermost. katharina.chaospott.de is the host were currently everything runs on.

**Comment by dbrgn** [comment]
The goal is that every configuration change on the server is reflected in this provisioning setup, so that at any time we can set up a new equivalent host and only have to transfer pure data from the old host to the new one.

Right now we only run Mattermost I think.

**Comment by gidsi** [comment]
So far i don't think anybody executed a single command manually on the server. So yeah, so far, its everything :)

Katharina is the current (temporary until we get something nicer) spaceapi server.
