### ISSUE TITLE
Cleanup

### ISSUE THREAD

**Issue by gidsi** [SpaceApi/provisioning#24]
So far we don't have an automatic cleanup, how do we want to take care of that?

Only idea that came to my mind is to kill the server once in a while and hope our setup doesn't break. Better than nothing but quite far from perfect :/

**Comment by rnestler** [comment]
> So far we don't have an automatic cleanup

Automatic cleanup of what? If we install stuff and then later on don't use it anymore and it doesn't get uninstalled?

We could just add the removal steps to the Ansible script. If it is already removed it won't change a thing. After some time we can clean up the Ansible script and remove the cleanup steps.

**Comment by gidsi** [comment]
Cleanup of the server, we can leave the stuff but that means that we are depending on something that already happened on the server without us noticing. 
Adding removal steps would definitely help the cause but e.g. i would also like to have an A/B system or something where we can always start with a "fresh" server to be sure that we can always provision a from scratch and have a running system.

**Comment by gidsi** [comment]
closed by #42
