### ISSUE TITLE
testing changes

### ISSUE THREAD

**Issue by gidsi** [SpaceApi/provisioning#25]
We don't have a proper way to check if changes break our setup. Fire up a vagrant and let the playbook run against it would be possible, but this way we can't test e.g. the lets encrypt certificates (which is a pain in the ass to test in general in my opinion).

Ideas anyone?

**Comment by rnestler** [comment]
Testing with vagrant or Docker or similar would be nice!

I don't think we can achieve 100% test coverage and probably will need to leave out stuff like lets-encrypt certificates. Otherwise we'd need a staging server which we kill once in a while to test everything.

**Comment by gidsi** [comment]
closed by #42
