### ISSUE TITLE
Dockerhub: too many requests

### ISSUE THREAD

**Issue by gidsi** [SpaceApi/provisioning#77]
We get an error from dockerhub:
```
Error response from daemon: toomanyrequests: 
You have reached your pull rate limit. 
You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit.
```

**Comment by dbrgn** [comment]
> The rate limits will be progressively lowered to a final state of 100 container image requests per six hours for anonymous usage, and 200 container image requests per six hours for free Docker accounts. Image requests exceeding these limits will be denied until the six hour window elapses. 

That's a request every 3.6 minutes without login and a request every 1.8 minutes with login.

**Comment by rnestler** [comment]
So just reduce our polling to once every hour or something and we are fine?

**Comment by dbrgn** [comment]
Probably. Note that this is about "container image requests" and not "requests per image", so if we want to keep 5 containers with different images up to date that's 5 requests per check :slightly_frowning_face:

**Comment by rnestler** [comment]
Well 5 containers * 6 hours is still just 30 requests per six hours, so we are fine :slightly_smiling_face: Alternatively we could just host a GitLab Docker registry and push our images there :slightly_smiling_face:
